### ISSUE TITLE
Would LiteralMatchPattern match symbols?

### ISSUE THREAD

**Issue by aaronshaf** [tc39/proposal-pattern-matching#52]
```
const foo = Symbol()

match (bar) {
  foo: 'cool'
}
```

**Comment by aaronshaf** [comment]
Any idea?

Appreciate y'all.

**Comment by littledan** [comment]
This is a great example of why it's sort of inherently difficult to evaluate expressions that are on the left-hand "match" side. I'm not how Symbols should integrate, personally.

**Comment by aaronshaf** [comment]
I'd like to avoid "primitive obsession" in my code. I'd rather use a set of symbols than strings or booleans for managing state.

**Comment by zkat** [comment]
Hey y'all! #65 has gotten merged, and a lot of issues have become irrelevant or significantly changed in context. Because of the magnitude of changes and subtle differences in things that seem similar, we've decided to just nuke all existing issues so we can start fresh. Thank you so much for the contributions and discussions and feel free to create new issues if something seems to still be relevant, and link to the original, related issue so we can have a paper trail (but have the benefit of that clean slate anyway).

That said, the new spec makes special mention of Symbol-based matching in the "future work" section, as well as talking a bit around the possibilities for this sort of feature.
