### ISSUE TITLE
Resolving ambiguity around identifiers

### ISSUE THREAD

**Issue by xixixao** [tc39/proposal-pattern-matching#61]
I believe that patterns should be consistent on any level. Hence you should be able to match against identifiers on any level, but also assign to them. I think this nicely combines with an explicit binding syntax, but would also benefit from not assigning to underscores. Altogether then:

```es6
match (something) {
  x: x // `x` is catch-all assignment
}

const y = 6;
match (something) {
  y as x: x // something has to equal `y`, then it is assigned to `x`
}

let x, y, z = ....;
match (something) {
  [x as _, y as _, z as _]: "Tuple x, y, z" // something has match a tuple of `x`, `y`, `z`
}

match (something) {
  [{x: 3} as tagged]: tagged.y, // if something is an array with single object which has a field x equal to 3, then `tagged` will refer to it
  _: "None tagged"
}
```

The binding syntax could be different, for example (as suggested elsewhere and used in Rust), `identifier@pattern`.

This avoid the following ambiguity:
```es6
const x = 6;
match (something) {
  [x]: "Single element array" // actually value in the array must be `6`
}

match (something) {
  [y]: "Single element array" // y is declared as a new variable
}

**Comment by zkat** [comment]
Hey y'all! #65 has gotten merged, and a lot of issues have become irrelevant or significantly changed in context. Because of the magnitude of changes and subtle differences in things that seem similar, we've decided to just nuke all existing issues so we can start fresh. Thank you so much for the contributions and discussions and feel free to create new issues if something seems to still be relevant, and link to the original, related issue so we can have a paper trail (but have the benefit of that clean slate anyway).

That said, I think the new spec pretty much covers the concerns in this issue, so I'm pretty comfortable saying it's resolved.
