### ISSUE TITLE
Handling of nullish / not-nullish ?

### ISSUE THREAD

**Issue by rattrayalex** [tc39/proposal-pattern-matching#62]
When I was working on a similar proposal for pattern-matching in LightScript, I did a bit of scraping of OCaml/Rust usages of `match` in a handful of repos. I found that a large majority (IIRC over 80%) of usages of `match` where checking `Some`/`None` or equivalent. 

In JavaScript, `Some`/`None` is typically represented as either `T | null`, `T | void`, or `T | null | void` (using Flow type syntax for shorthand). The last is a bit of an antipattern, but is also very common, and at times the most pragmatic. 

I would love to see an ergonomic way of expressing, eg; 

```jsx
const foo = match (maybeT) {
  ??: maybeT, // not nullish
  else: "some default value"
}
const bar = match (maybeT) {
  null, undefined: "some default value", // nullish
  String: "hello " + maybeT,
  [...]: "hello " + maybeT.join(', '),
}
```

Perhaps there already exists a preferred pattern (perhaps it's even what I have written above) with this feature; I am simply curious to hear if these cases have been considered, and what the recommended approach to handling them would be. 

(Obviously, my "not nullish" suggestion is dependent on the other nullish proposals)

**Comment by zkat** [comment]
Hey y'all! #65 has gotten merged, and a lot of issues have become irrelevant or significantly changed in context. Because of the magnitude of changes and subtle differences in things that seem similar, we've decided to just nuke all existing issues so we can start fresh. Thank you so much for the contributions and discussions and feel free to create new issues if something seems to still be relevant, and link to the original, related issue so we can have a paper trail (but have the benefit of that clean slate anyway).

Furthermore, the issue of null/nullish is covered in some detail by the new spec! Please take a look and see what you think.
