### ISSUE TITLE
Bikeshed : undefiend matching

### ISSUE THREAD

**Issue by c-dante** [tc39/proposal-pattern-matching#67]
https://github.com/tc39/proposal-pattern-matching#--undefined-matching

Trying to get the vote in for this now -- but the special case option, where `undefined` is treated as the primitive value and not as a variable. I would argue it's an extreme anti-pattern to re-define "undefined", and the fact that this feels like something that will happen:
```js
const foo = (obj = {}) => obj.prop match {
  ...
  undefined => // object does not have prop
}
```

Pushes me to support treating it as always the primitive value.

As a tangent, I don't support the [equality-punning for null](https://github.com/tc39/proposal-pattern-matching#--automatic-equality-punning-for-null), since that feels as a special case work around for a similar problem that this proposal handles, and the change of functionality from `===` to `==` just for null. But that argument is weak for me, since I imagine a lot of people don't care if you hit `undefined` in the `null` branch.

**Comment by zkat** [comment]
@c-dante since what you're describing is what the current spec is currently describing, do you mind closing this so we can keep the repo issues under control? I don't feel like there's anything actionable with this particular issue, and I totally appreciate you dropping a note about this. I pretty much agree with you and don't foresee this changing unless the committee has huge issues with either of them.
