### ISSUE TITLE
Doesn't this duplicate es-extensible-collection-literal?

### ISSUE THREAD

**Issue by alex-weej** [tc39/proposal-pattern-matching#82]
https://github.com/alex-weej/es-extensible-collection-literal

:(

**Comment by alex-weej** [comment]
Oh, I see it was namedropped... Not sure why no one reached out to me but I'm glad there's some motion in this area.

**Comment by tabatkins** [comment]
Yeah, this subsumes, not duplicates. ^_^

**Comment by alex-weej** [comment]
So far the collection literals spec is lighter on details than my original proposal. Seems a bit of a *faux pas* to base a new proposal on an old one without attempting to involve the original author?

Thanks

**Comment by tabatkins** [comment]
Kat made this proposal without knowledge of your older one; they were pointed to some historical proposals for this by AWB earlier today, but I don't think he pointed to your proposal specifically.

(The fact that both use `#` is a fun coincidence from the fact that we're running out of ASCII punctuation.)

**Comment by zkat** [comment]
@alex-weej I didn't reach out because I literally just did the refactor and hadn't started any work on it.

@tabatkins I knew about the proposal, that's why the tagged collections proposal links to it.

**Comment by zkat** [comment]
Err, longer answer: I was originally working on this problem from a different end. I was trying to get a good way to have custom matchers of some sort (called "extractors" in a previous version, from the Scala term), and was not considering the idea of custom constructors _at all_. I just needed convenient literal patternmatching syntax. I got stuck on some grammar stuff and then started thinking about it more, and I ran into your proposal, which tackled this from the _other_ end (creation), and realized that this whole feature would be better off if all three bits (matching, destructuring, and construction) were unified under a single, analogous syntax.

So I tore out everything having to do with extractors from the previous proposal, and I sketched this sub-proposal out as a possible direction that would solve the custom matchers problem while also solving the literal construction and extensible destructuring problem, all with a single thing.

And the sub-proposal is intentionally thin on details because I want to make sure the semantics that get defined actually work _for all three things at the same time_. That means, I suspect, that I might not be able (or maybe should or shouldn't) pick up the semantics @alex-weej defined in their own literals proposal. My priority is for everything to work in concert, not optimize for one of the use-cases.

The fact that you found it less than 12h after I pushed the very rough initial sketch tells me that no, I didn't need to worry about reaching out to you. I'm not being quiet about this and I figured I would do it eventually when I had more than a couple of code blocks in a scratchpad.

As far as where to go from here: I'm planning on focusing my work on the `match` expression itself, and its semantics. I might poke at the custom literals thing a bit as I go along, but I don't want that to get hashed out in too much detail until match is more solid, so we actually know what it will need.

At that point (probably if/after the "core" proposal hits stage 1... I'm trying in May), I plan on spinning off the tagged collection literals proposal into its own repo, and its own standalone proposal that happens to reference the separate pattern matching proposal. I don't expect them to hit stage 1 at the same time, and I wouldn't want them to.

**Comment by alex-weej** [comment]
A colleague messaged me with your Twitter post pointing out that it looked the same idea - which seemed to get a lot more attention than my es-discuss posting of 31 July 2017 - https://mail.mozilla.org/pipermail/es-discuss/2017-July/048713.html - I guess mailing lists are a bit old hat these days...

Anyway, regardless of how we got here, seems a bit inefficient to spin off an entirely new proposal. Why not contribute, champion or even coauthor es-extensible-collection-literal?

**Comment by zkat** [comment]
it's a stage 0 proposal, and barely even that. It's pretty much fine to rejigger things aggressively at this stage. I also would rather have immense amounts of flexibility in making sweeping changes to the semantics because I want to make it all correspond to destructuring and matching in a consistent and efficient way. That almost certainly means I'm gonna be making technical choices you'll find undesirable, and that's ok, 'cause this is all exploratory.

**Comment by tabatkins** [comment]
> I knew about the proposal, that's why the tagged collections proposal links to it.

D'oh, sorry for the misinformation. ^_^  (*I* didn't know about Alex's repo, just the historical stuff from es-discuss.)

**Comment by zkat** [comment]
p.s. if you wanna extend your existing proposal include MatchPattern and BindingPattern, I'm cool with just helping you and champion that one. I just didn't get the impression you wanted to take care of those bits. tbh, getting that load off my shoulder would be lovely, but also I've got a lot of constraints in mind for what their shared semantics should be in order to mesh well with the match proposal so I might end up nagging you a ton about it, and that'd be obnoxious of me at stage 0.

**Comment by alex-weej** [comment]
> I just didn't get the impression you wanted to take care of those bits

I didn't even acknowledge any overlap with pattern matching because any syntactical literal has the same issue. Believe me, I want pattern matching in the language, too!

Let's talk about it shortly anyway.

**Comment by zkat** [comment]
I think the misunderstanding here has been cleared up, and further action would need separate discussions than whether or not this proposal overrules the other one (it's intended to)
